In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
mba = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\mba.csv")
mba

     Datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
..        ...     ...   ...
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

[773 rows x 3 columns]

In [8]:
del mba['Datasrno']

In [9]:
mba

     workex  gmat
0        21   720
1       107   640
2        57   740
3        99   690
4       208   710
..      ...   ...
768      88   620
769     132   670
770      28   610
771      10   610
772      52   620

[773 rows x 2 columns]

In [10]:
mba = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\mba.csv")
mba

     Datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
..        ...     ...   ...
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

[773 rows x 3 columns]

In [11]:
len(mba)

773

In [12]:
len(mba.columns)

3

In [13]:
mba.shape

(773, 3)

In [14]:
mba.columns

Index(['Datasrno', 'workex', 'gmat'], dtype='object')

In [15]:
mba.dtypes

Datasrno    int64
workex      int64
gmat        int64
dtype: object

In [18]:
mba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datasrno  773 non-null    int64
 1   workex    773 non-null    int64
 2   gmat      773 non-null    int64
dtypes: int64(3)
memory usage: 18.2 KB

In [19]:
mba.head()

   Datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710

In [20]:
mba.tail()

     Datasrno  workex  gmat
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

In [21]:
mba.describe()

        Datasrno     workex        gmat
count  773.00000  773.00000  773.000000
mean   387.00000   57.50194  711.164295
std    223.29017   27.38682   29.339714
min      1.00000    9.00000  600.000000
25%    194.00000   41.00000  690.000000
50%    387.00000   52.00000  710.000000
75%    580.00000   69.00000  730.000000
max    773.00000  279.00000  780.000000

In [22]:
# To convert rows into columns
mba.describe().transpose()

          count        mean         std    min    25%    50%    75%    max
Datasrno  773.0  387.000000  223.290170    1.0  194.0  387.0  580.0  773.0
workex    773.0   57.501940   27.386820    9.0   41.0   52.0   69.0  279.0
gmat      773.0  711.164295   29.339714  600.0  690.0  710.0  730.0  780.0

In [23]:
mba['gmat']

0      720
1      640
2      740
3      690
4      710
      ...
768    620
769    670
770    610
771    610
772    620
Name: gmat, Length: 773, dtype: int64

In [24]:
mba.mean()

Datasrno    387.000000
workex       57.501940
gmat        711.164295
dtype: float64

In [25]:
mba['gmat'].mean()

711.1642949547219

In [26]:
mba.std()

Datasrno    223.290170
workex       27.386820
gmat         29.339714
dtype: float64

In [27]:
mba.var()

Datasrno    49858.500000
workex        750.037885
gmat          860.818827
dtype: float64

In [28]:
mba.min()

Datasrno      1
workex        9
gmat        600
dtype: int64

In [29]:
mba.max()

Datasrno    773
workex      279
gmat        780
dtype: int64

In [30]:
mba.median()

Datasrno    387.0
workex       52.0
gmat        710.0
dtype: float64

In [33]:
mba['gmat'].mode()

0    710
dtype: int64

In [34]:
 mba['workex'].mode()

0    45
dtype: int64

In [4]:
# Import scipy.stats for mode, skewness and kurtosis
from scipy.stats import skew
skew = skew(mba['gmat'])
skew

-0.594320384238288

In [8]:
from scipy.stats import skew
skew1 = skew(mba['workex'])
skew1

2.6034719936121817

In [6]:
from scipy.stats import mode
mode(mba['gmat'])

ModeResult(mode=array([710], dtype=int64), count=array([178]))

In [9]:
from scipy.stats import mode
mode(mba['workex'])

ModeResult(mode=array([45], dtype=int64), count=array([60]))

In [11]:
from scipy.stats import kurtosis
kurtosis = kurtosis(mba['gmat'])
kurtosis

1.1518763065845246

In [13]:
from scipy.stats import kurtosis
kurtosis1 = kurtosis(mba['workex'])
kurtosis1

13.310430657188096

# Categorical Analysis

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
wbcd = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\wbcd.csv")
wbcd

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,87139402,B,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,...,13.50,15.64,86.97,549.1,0.1385,0.1266,0.12420,0.09391,0.2827,0.06771
1,8910251,B,10.60,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,...,11.88,22.94,78.28,424.8,0.1213,0.2515,0.19160,0.07926,0.2940,0.07587
2,905520,B,11.04,16.83,70.92,373.2,0.10770,0.07804,0.03046,0.02480,...,12.41,26.44,79.93,471.4,0.1369,0.1482,0.10670,0.07431,0.2998,0.07881
3,868871,B,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,...,11.92,15.77,76.53,434.0,0.1367,0.1822,0.08669,0.08611,0.2102,0.06784
4,9012568,B,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.02657,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.13620,0.08178,0.2487,0.06766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,911320502,B,13.17,18.22,84.28,537.3,0.07466,0.05994,0.04859,0.02870,...,14.90,23.89,95.10,687.6,0.1282,0.1965,0.18760,0.10450,0.2235,0.06925
565,898677,B,10.26,14.71,66.20,321.6,0.09882,0.09159,0.03581,0.02037,...,10.88,19.48,70.89,357.1,0.1360,0.1636,0.07162,0.04074,0.2434,0.08488
566,873885,M,15.28,22.41,98.92,710.6,0.09057,0.10520,0.05375,0.03263,...,17.80,28.03,113.80,973.1,0.1301,0.3299,0.36300,0.12260,0.3175,0.09772
567,911201,B,14.53,13.98,93.86,644.2,0.10990,0.09242,0.06895,0.06495,...,15.80,16.93,103.10,749.9,0.1347,0.1478,0.13730,0.10690,0.2606,0.07810
568,9012795,M,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,...,22.69,21.84,152.10,1535.0,0.1192,0.2840,0.40240,0.19660,0.2730,0.08666

In [16]:
del wbcd['id']
wbcd

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,B,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,0.1959,...,13.50,15.64,86.97,549.1,0.1385,0.1266,0.12420,0.09391,0.2827,0.06771
1,B,10.60,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,0.1922,...,11.88,22.94,78.28,424.8,0.1213,0.2515,0.19160,0.07926,0.2940,0.07587
2,B,11.04,16.83,70.92,373.2,0.10770,0.07804,0.03046,0.02480,0.1714,...,12.41,26.44,79.93,471.4,0.1369,0.1482,0.10670,0.07431,0.2998,0.07881
3,B,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,0.1771,...,11.92,15.77,76.53,434.0,0.1367,0.1822,0.08669,0.08611,0.2102,0.06784
4,B,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.02657,0.1721,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.13620,0.08178,0.2487,0.06766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,B,13.17,18.22,84.28,537.3,0.07466,0.05994,0.04859,0.02870,0.1454,...,14.90,23.89,95.10,687.6,0.1282,0.1965,0.18760,0.10450,0.2235,0.06925
565,B,10.26,14.71,66.20,321.6,0.09882,0.09159,0.03581,0.02037,0.1633,...,10.88,19.48,70.89,357.1,0.1360,0.1636,0.07162,0.04074,0.2434,0.08488
566,M,15.28,22.41,98.92,710.6,0.09057,0.10520,0.05375,0.03263,0.1727,...,17.80,28.03,113.80,973.1,0.1301,0.3299,0.36300,0.12260,0.3175,0.09772
567,B,14.53,13.98,93.86,644.2,0.10990,0.09242,0.06895,0.06495,0.1650,...,15.80,16.93,103.10,749.9,0.1347,0.1478,0.13730,0.10690,0.2606,0.07810
568,M,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,0.1973,...,22.69,21.84,152.10,1535.0,0.1192,0.2840,0.40240,0.19660,0.2730,0.08666

In [17]:
# To give the count of each category 
wbcd['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [19]:
freq = pd.crosstab(index = wbcd['diagnosis'], columns = "count")
freq

col_0      count
diagnosis
B            357
M            212

In [24]:
freq/freq.sum()*100

col_0          count
diagnosis
B          62.741652
M          37.258348

In [25]:
# To replace the function used to change the label name in the rows
wbcd['diagnosis'].replace({"B":"Benign","M":"Malignant"},inplace=True)
wbcd

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,Benign,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,0.1959,...,13.50,15.64,86.97,549.1,0.1385,0.1266,0.12420,0.09391,0.2827,0.06771
1,Benign,10.60,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,0.1922,...,11.88,22.94,78.28,424.8,0.1213,0.2515,0.19160,0.07926,0.2940,0.07587
2,Benign,11.04,16.83,70.92,373.2,0.10770,0.07804,0.03046,0.02480,0.1714,...,12.41,26.44,79.93,471.4,0.1369,0.1482,0.10670,0.07431,0.2998,0.07881
3,Benign,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,0.1771,...,11.92,15.77,76.53,434.0,0.1367,0.1822,0.08669,0.08611,0.2102,0.06784
4,Benign,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.02657,0.1721,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.13620,0.08178,0.2487,0.06766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,Benign,13.17,18.22,84.28,537.3,0.07466,0.05994,0.04859,0.02870,0.1454,...,14.90,23.89,95.10,687.6,0.1282,0.1965,0.18760,0.10450,0.2235,0.06925
565,Benign,10.26,14.71,66.20,321.6,0.09882,0.09159,0.03581,0.02037,0.1633,...,10.88,19.48,70.89,357.1,0.1360,0.1636,0.07162,0.04074,0.2434,0.08488
566,Malignant,15.28,22.41,98.92,710.6,0.09057,0.10520,0.05375,0.03263,0.1727,...,17.80,28.03,113.80,973.1,0.1301,0.3299,0.36300,0.12260,0.3175,0.09772
567,Benign,14.53,13.98,93.86,644.2,0.10990,0.09242,0.06895,0.06495,0.1650,...,15.80,16.93,103.10,749.9,0.1347,0.1478,0.13730,0.10690,0.2606,0.07810
568,Malignant,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,0.1973,...,22.69,21.84,152.10,1535.0,0.1192,0.2840,0.40240,0.19660,0.2730,0.08666

In [27]:
# To replace the column names in the dataset
wbcd.rename(columns={'radius_mean':'Mean Radius'},inplace=True)
wbcd

,diagnosis,Mean Radius,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,Benign,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,0.1959,...,13.50,15.64,86.97,549.1,0.1385,0.1266,0.12420,0.09391,0.2827,0.06771
1,Benign,10.60,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,0.1922,...,11.88,22.94,78.28,424.8,0.1213,0.2515,0.19160,0.07926,0.2940,0.07587
2,Benign,11.04,16.83,70.92,373.2,0.10770,0.07804,0.03046,0.02480,0.1714,...,12.41,26.44,79.93,471.4,0.1369,0.1482,0.10670,0.07431,0.2998,0.07881
3,Benign,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,0.1771,...,11.92,15.77,76.53,434.0,0.1367,0.1822,0.08669,0.08611,0.2102,0.06784
4,Benign,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.02657,0.1721,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.13620,0.08178,0.2487,0.06766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,Benign,13.17,18.22,84.28,537.3,0.07466,0.05994,0.04859,0.02870,0.1454,...,14.90,23.89,95.10,687.6,0.1282,0.1965,0.18760,0.10450,0.2235,0.06925
565,Benign,10.26,14.71,66.20,321.6,0.09882,0.09159,0.03581,0.02037,0.1633,...,10.88,19.48,70.89,357.1,0.1360,0.1636,0.07162,0.04074,0.2434,0.08488
566,Malignant,15.28,22.41,98.92,710.6,0.09057,0.10520,0.05375,0.03263,0.1727,...,17.80,28.03,113.80,973.1,0.1301,0.3299,0.36300,0.12260,0.3175,0.09772
567,Benign,14.53,13.98,93.86,644.2,0.10990,0.09242,0.06895,0.06495,0.1650,...,15.80,16.93,103.10,749.9,0.1347,0.1478,0.13730,0.10690,0.2606,0.07810
568,Malignant,21.37,15.10,141.30,1386.0,0.10010,0.15150,0.19320,0.12550,0.1973,...,22.69,21.84,152.10,1535.0,0.1192,0.2840,0.40240,0.19660,0.2730,0.08666